// Listing of all the infrastructure unit tests
define([
	"./responsiveColumnsVisibility/Test",
	"./transitionTypes/Test",
	"./viewLayout/Test",
	"./appStatus/Test",
	"./transitionVisibility/Test",
	"./nlsLabels/Test",
	"./viewDataAndParams/Test",
	"./hideView/Test",
	"./multipleAndNestedViewsActivateCalls/Test",
	"./multipleAndNestedViewsActivateCalls/TestConstraints",
	"./nestedViewsActivateCalls/Test",
	"./sidePaneViewsActivateCalls/Test",
	"./historyController/Test",
	"./jqm/hideViewJqm/Test",
	"./jqm/transitionVisibility/Test",
	"./dstoreMemory/Test"
]);
